apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onboarding-app-argo-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/propalparolnapervom/ait-onboarding-app-cd
    targetRevision: HEAD
    path: ait-onboarding-app-chart
    helm:
      releaseName: onboard
      valueFiles: # relative to the spec.source.path dir defined above
        - ../env/dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: onboarding-app-ns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
