apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-onboarding-app
  labels:
    app: onboarding-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: onboarding-app
  template:
    metadata:
      labels:
        app: onboarding-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.exposed_port }}
              protocol: TCP
