replicaCount: 1

namespace: default

image:
  repository: ppnp/ait-onboarding-app
  tag: "0.0.2"
  pullPolicy: Always
  exposed_port: 80

service:
  name: onboarding-app-service
  type: NodePort
  http_port: 90
  http_targetPort: 80
  http_nodePort: 31080

ingress:
  name: onboarding-app-ingress
  host: onboarding-app.sergii-b-playground.automat-it.io
  load_balancer_scheme: internet-facing # internal, internet-facing
  load_balancer_name: sergii-cluster-public-alb
